const $ = (id) => document.getElementById(id);
const fmt = (n) => Number.isFinite(Number(n)) ? Math.round(Number(n)).toLocaleString('en-US') : '—';
const clamp = (n, a, b) => Math.max(a, Math.min(b, n));
const demo = { cpu: 18, ram: 31, gpus: [{ id: 0, name: 'GPU', util: 0, memory: 0, memoryTotal: 0, temp: null, power: null, powerLimit: null, clock: null, fan: null, pstate: '—' }] };
let intervalMs = 1200, timer = null, backend = 'auto', histories = [18,20,17,21,19,18,22,20,18,19,18,18];

function set(id, value) { const el = $(id); if (el) el.textContent = value; }
function renderCpu(host) {
  const cpu = Number(host?.cpuPercent);
  const logical = Number(host?.logicalProcessors);
  const physical = Math.max(1, Math.round(logical / 2));
  set('cpuModel', host?.cpuModel || '本机处理器'); set('cpuSub', host?.cpuModel ? 'PROCESSOR TELEMETRY' : 'PROCESSOR MODEL UNAVAILABLE');
  set('cpuPct', Number.isFinite(cpu) ? `${cpu.toFixed(1)}%` : '—'); set('cpuLoadBig', Number.isFinite(cpu) ? `${cpu.toFixed(1)}%` : '—'); set('cpuCores', logical ? physical : '—'); set('cpuThreads', logical || '—');
  $('cpuBar').style.width = `${clamp(cpu || 0, 0, 100)}%`; histories.push(cpu || 0); histories = histories.slice(-24); $('cpuBars').innerHTML = histories.map(v => `<i style="height:${clamp(8 + v * .75, 8, 32)}px"></i>`).join('');
}
function renderMemory(memory) {
  const total = Number(memory?.total), used = Number(memory?.used), pct = total ? used / total * 100 : null;
  const totalGb = total ? total / 1073741824 : null, usedGb = used ? used / 1073741824 : null;
  set('ramTitle', totalGb ? `${totalGb.toFixed(1)} GB` : '— GB'); set('ramSub', '内存总量 · DDR 型号未识别'); set('ramPct', Number.isFinite(pct) ? `${pct.toFixed(1)}%` : '—'); set('ramUsed', usedGb ? `${usedGb.toFixed(1)} GB` : '—'); set('ramAvailable', totalGb && usedGb ? `${(totalGb - usedGb).toFixed(1)} GB` : '—'); $('ramBar').style.width = `${clamp(pct || 0, 0, 100)}%`; $('memoryRing').style.background = `conic-gradient(var(--violet) ${(pct || 0) * 3.6}deg,#20202e 0deg)`;
}
function renderGpus(gpus) {
  const list = Array.isArray(gpus) ? gpus : []; set('gpuCount', `${list.length} / ${list.length}`); $('gpuGrid').innerHTML = list.length ? list.map(gpu => { const memPct = gpu.memoryTotal ? gpu.memory / gpu.memoryTotal * 100 : 0; const power = Number.isFinite(gpu.power) ? `${Math.round(gpu.power)} W` : '—'; return `<article class="gpu-card"><span class="gpu-code">GPU${gpu.id} // ONLINE</span><h3>${gpu.name || 'NVIDIA GPU'}</h3><p>PCIe ACCELERATOR · P-STATE ${gpu.pstate || '—'}</p><div class="gpu-metrics"><div class="gpu-metric"><span>核心利用率</span><strong class="cyan">${Number.isFinite(gpu.util) ? Math.round(gpu.util) : '—'}%</strong><div class="bar"><i style="width:${clamp(gpu.util || 0,0,100)}%"></i></div></div><div class="gpu-metric"><span>显存占用</span><strong>${fmt(gpu.memory)} <small>/ ${fmt(gpu.memoryTotal)} MB</small></strong><div class="bar"><i style="width:${clamp(memPct,0,100)}%"></i></div></div><div class="gpu-metric"><span>温度</span><strong class="amber">${Number.isFinite(gpu.temp) ? Math.round(gpu.temp) : '—'}°C</strong></div><div class="gpu-metric"><span>功耗</span><strong>${power} <small>/ ${Number.isFinite(gpu.powerLimit) ? Math.round(gpu.powerLimit) : '—'} W</small></strong></div></div></article>`; }).join('') : '<article class="gpu-card"><span class="gpu-code">GPU ARRAY // OFFLINE</span><h3>未检测到 GPU</h3><p>等待 nvidia-smi 或 rocm-smi 返回设备信息</p></article>';
}
function renderInference(inference) {
  const loaded = Boolean(inference?.connected && inference?.loaded && inference?.model); const metrics = inference?.metrics || {}; const slots = inference?.slots || {}; set('backendName', inference?.backend || '未检测到后端'); set('modelStatus', loaded ? '在线' : '未加载模型'); set('modelName', loaded ? inference.model : '【未加载模型】'); set('modelMeta', loaded ? `${inference.url || '本机后端'} · ${slots.active ? 'ACTIVE GENERATION' : 'READY / IDLE'}` : '等待本机后端上报模型参数'); set('modelArch', inference?.details?.architecture || '—'); set('modelQuant', inference?.details?.quantization || '—'); set('modelContext', inference?.details?.contextLength ? `${fmt(inference.details.contextLength)} tokens` : '—');
  const gen = Number(metrics.generationSpeed), prompt = Number(metrics.promptSpeed); set('genSpeed', Number.isFinite(gen) ? gen.toFixed(1) : '—'); set('promptSpeed', Number.isFinite(prompt) ? fmt(prompt) : '—'); set('genWindow', Number.isFinite(gen) ? (slots.active ? '实时采样' : '结束前最后值') : '等待指标'); set('promptWindow', Number.isFinite(prompt) ? (slots.active ? '实时采样' : '结束前最后值') : '等待指标'); const used = Number(slots.used), total = Number(slots.total); set('contextUsed', Number.isFinite(used) ? fmt(used) : '—'); set('contextTotal', Number.isFinite(total) ? `/ ${fmt(total)}` : ''); const pct = total ? used / total * 100 : 0; $('contextBar').style.width = `${clamp(pct, 0, 100)}%`; set('contextFoot', Number.isFinite(used) ? `${pct.toFixed(1)}% · ${slots.active ? 'ACTIVE' : 'LAST SNAPSHOT'}` : '等待推理请求'); set('taskStatus', loaded ? (slots.active ? '生成中' : '无运行任务') : '未加载模型'); set('taskTitle', loaded ? (slots.active ? (slots.task || '当前推理请求') : '当前没有活动推理请求') : '【未加载模型】'); set('taskProgress', Number.isFinite(used) && Number.isFinite(total) ? `${fmt(used)} / ${fmt(total)} tokens` : '—'); set('taskId', slots.active ? 'LIVE TASK' : 'IDLE');
}
function apply(data) { if (!data) return; set('clock', new Date().toLocaleTimeString('en-GB', { hour12: false })); set('dataSource', `${(data.gpus?.length ? 'GPU：' + (data.source === 'rocm-smi' ? 'rocm-smi' : 'nvidia-smi') : 'GPU：未检测到 GPU 驱动')} · 主机：Task Manager · ${data.inference?.backend || '后端未连接'}`); const power = Number(data.power?.total); set('totalPower', Number.isFinite(power) ? fmt(power) : '—'); set('powerSummary', Number.isFinite(power) ? `GPU POWER BUS · ${data.power.known || 0}/${data.power.gpuCount || 0} VALID` : 'GPU POWER BUS'); renderCpu(data.host); renderMemory(data.memory); renderGpus(data.gpus); renderInference(data.inference); window.renderDailyStats?.(data.inference?.daily); const choices = [{ key: 'auto', name: '自动' }, ...(data.inference?.backends || []).map(b => ({ key: b.key, name: `${b.name}${b.loaded ? ' · 已加载' : ''}` }))]; $('backendSelect').innerHTML = choices.map(c => `<option value="${c.key}">${c.name}</option>`).join(''); $('backendSelect').value = backend; }
async function sample() { try { const response = await fetch(`/api/status?backend=${encodeURIComponent(backend)}`, { cache: 'no-store' }); if (response.ok) apply(await response.json()); } catch (_) {} timer = setTimeout(sample, intervalMs); }
$('intervalSlider').addEventListener('input', e => { intervalMs = Number(e.target.value) * 1000; set('intervalValue', `${Number(e.target.value).toFixed(1)}s`); clearTimeout(timer); sample(); }); $('backendSelect').addEventListener('change', e => { backend = e.target.value; clearTimeout(timer); sample(); }); $('refreshBtn').addEventListener('click', () => { clearTimeout(timer); sample(); }); sample();
